### ISSUE TITLE
Do we need to cache `extension_loaded` result?

### ISSUE THREAD

**Issue by Hywan** [hoaproject/Core#58]
Several questions:
  1. does it impact performance?
  2. how does it impact performance?

Depending on these answers:
  3. should we introduce a workaround in `Hoa\Core\Consistency`?
  4. should we patch [php-src](https://github.com/php/php-src/) and [HHVM](https://github.com/facebook/hhvm/)?

Original discussion: https://github.com/hoaproject/Database/pull/19.

**Comment by Metalaka** [comment]
Since 5.6.0, php-src's opcache should do the job.
Source: [php-src/ext/opcache/Optimizer/pass1_5.c](https://github.com/php/php-src/blob/ef1b588f6a39bcc2c0d5fad9f2094bb011aeaf0b/ext/opcache/Optimizer/pass1_5.c#L426-508),  [`extension_loaded` function](https://github.com/php/php-src/blob/d5b78cec641173f3e37b9bad1e575fb5b646196c/Zend/zend_builtin_functions.c#L2676).

Moreover the cost of calling a function (without the implementation) is equivalent to the `extension_loaded` cost.

```php
class Hoa_Consistency {
    public static function extension_loadedCache($name) {
        return true;
    }
}
$i = 0;
$n = 1000000;

// run bench
$t1 = microtime(true);

for (; $i < $n; ++$i) {
    extension_loaded('pdo');
}

echo (microtime(true) - $t1), "\n";

$i = 0;
$t2 = microtime(true);

for (; $i < $n; ++$i) {
    Hoa_Consistency::extension_loadedCache('pdo');
}

echo (microtime(true) - $t2), "\n";
```

```sh
$ php 5.5
0.15259599685669
0.15605688095093

$ php 5.6
0.17508316040039
0.14802479743958

$ php 7.0rc1
0.11212182044983
0.091778993606567
```

**Comment by Hywan** [comment]
Thanks @Metalaka. The more code we have, the more to maintain and to test. In this case, it does not make a huge difference, so we can close it!
